FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    python3 \
    nodejs \
    coreutils \
    findutils \
    && rm -rf /var/lib/apt/lists/*

# Ensure 'node' is available
RUN ln -sf /usr/bin/nodejs /usr/bin/node

# Create unprivileged sandbox user
RUN groupadd -g 1000 sandbox && \
    useradd  -u 1000 -g sandbox -M -s /bin/false sandbox

USER 1000:1000